# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Yuchi Ishikawa
title: Graduate Student majoring in Computer Vision
email: yishikawa[at]aoki-medialab.jp
# phone: Your phone number (optional)
website: https://github.com/yiskw713

# Social links
twitter_username: yiskw713
github_username:  yiskw713
# dribbble_username: jekyll
facebook_username: yuchi.ishikawa.7
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: 裕地-石川-126b39186
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | 
  I'm a first-year Master's student majoring in Electronics and Computer Vision in the dept. of Electronics and Electrical Engineering at Keio University.<br>
  My research interests are Machine Learning, Computer Vision(Semantic Segmentation and Action Recognition) and Robot Vision(Affordance and Motion Analysis). <br>
  Now I'm working on these topics;
    * Function Detection of an object (e.g. Affordance)
    * Action Recognition
    * Semantic Segmentation
    * Object Detection  

  I'm full of curiosity. I always want to acquire a lot of knowledge and catch up with cutting-edge technology.<br>
  I also love traveling, taking a picture, running in marathons, listening to music and so on. <br>
  If you get interested in me, do NOT hesitate to contact me!!<br>

# Education Section
education_title: Education #(Use this to override about education section title)

# Experience Section
experience_title: Work Experience #(Use this to override about experience section title)

# Publications Section
publications_title: Publications #(Use this to override about projects section title)
publications_content: |
  ## <b>Journal</b>
  * (Under Review)

  ## <b>International Conference</b>
  * Haruya Ishikawa, <b>Yuchi Ishikawa</b>, Shuichi Akizuki, Yoshimitsu Aoki,
    Human-Object Maps for Daily Activity Recognition, International Conference on Machine Vision Applications(MVA 2019)
  * (Under Review)

  ## <b>Domestic Conference</b>
  *	<b>石川裕地</b>，石川晴也，秋月秀一，青木義満，操作タスク入力に基づく物体の機能部推定，動的画像処理実利用化ワークショップ2019(DIA 2019)
  * <b>石川裕地</b>，石川晴也，秋月秀一，青木義満，操作タスクと指示対象クラスの入力による物体の機能部推定，第25回画像センシングシンポジウム(SSII 2019)
  * 秋月秀一，<b>石川裕地</b>，石川晴也，青木義満，非定常状態の理解とシーン復元のための物体の操作方法推定，動的画像処理実利用化ワークショップ2019(DIA 2019)

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Sholorship Section
scholorship_title: Scholorship

# Skills Section
skills_title: Skills
skills_content: | # this will include new lines to allow paragraphs
  ## <b>Language</b>
  <mark>Japanease</mark> <mark>English</mark>
  
  ## <b>Programming</b>
  <mark>Python</mark> <mark>C/C++</mark> <mark>HTML/CSS</mark>

  ## <b>Data Science</b>
  <mark>Numpy</mark> <mark>Pandas</mark> <mark>Pytorch</mark> <mark>MatLab</mark>

  ## <b>Computer Vision</b>
  <mark>Machine Learning</mark> <mark>Affordance</mark> <mark>Motion Analysis</mark> <mark>3D Point Cloud</mark> 
  <mark>Semantic Segmentation</mark> <mark>Action Recognition</mark> <mark>Object Detection</mark>

# More Section
more_title: When I'm Not Researching
more_content: | # this will include new lines to allow paragraphs
  When I'm not in Lab., I put my free time into my hobbies or hang out with my friends, though I love research and spend most of my time studying.<br>
  When I take a long vaction, I always do travel all over Japan or the world.
  I love traveling and I've experienced backpacking many times such as traveling across Japan by bike, crossing America by recreationl vehicle, 
  hitchhiking, survival on an uninhabited island, camping in Africa and so on.<br>
  Meeting people who have different backgrounds enriched my mind and changed me dramatically.<br>
  And I like taking pictures as I can keep my trips as a memory. I often enjoy taking pictures of landscape, night view and starry sky.<br>
  
  I also like listening to music, watching comedians shows, competitive programming and drinking coffee or tea.<br>
  These days, I'm carzy about running in marathons. I've completed a full marathon twice and I'm going to participate in marathons more and more.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
